### ISSUE TITLE
Can you change the username to give for jabberd project?

### ISSUE THREAD

**Issue by Neustradamus** [jabberd/RouterOS_Tools#1]
Can you change the username to give for jabberd project?

What is your email address?

Thanks in advance.

**Comment by jabb3rd** [comment]
You're welcome. I used this name for some years, but it's origin is, of course, because of jabberd XMPP server. I used it a long time ago, and kinda loved it.

**Comment by Neustradamus** [comment]
@jabb3rd: Thanks a lot!
